apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: fast
provisioner: kubernetes.io/aws-ebs
parameters:
  type: io1
  iopsPerGB: "1"
  fsType: ext4
---
apiVersion: v1
kind: Service
metadata:
  name: opscenter-ext-lb
  labels:
    app: opscenter
spec:
  type: NodePort
  ports:
  - port: 8888
    nodePort: 30888
    name: opsc-gui-port
  selector:
    app: opscenter
---
apiVersion: v1
kind: Service
metadata:
  name: opscenter
  labels:
    app: opscenter
spec:
  ports:
  - port: 8888
    name: opsc-gui-port
  - port: 61620
    name: port-61620
  clusterIP: None
  selector:
    app: opscenter
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: opscenter
spec:
  serviceName: "opscenter"
  replicas: 1
  template:
    metadata:
      labels:
        app: opscenter
    spec:
      containers:
        - name: opscenter
          image: datastax/dse-opscenter:6.5.0
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: "1"
              memory: "2000Mi"
          env:
          - name: DS_LICENSE
            value: accept
          ports:
          - containerPort: 8888
            name: opsc-gui-port
          - containerPort: 61620
            name: port-61620
          volumeMounts:
          - name: secrets-volume
            mountPath: /secrets
      volumes:
      - name: secrets-volume
        secret:
          secretName: dse-secrets
          items:
          - key: identity.jks
            path: .keystore
          - key: cacerts #TODO this should be a configMap, but k8s doesn't support binary files in config maps until 1.10 (we're on 1.9)
            path: cacerts
---
apiVersion: v1
kind: Service
metadata:
  name: dse 
  labels:
    app: dse
spec:
  ports:
  - port: 9142
    name: tls-cql-port
  clusterIP: None
  selector:
    app: dse
---
apiVersion: v1
kind: Service
metadata:
  name: dse-lb
  labels:
    app: dse
spec:
  type: NodePort
  ports:
  - port: 9142
    nodePort: 30943
    name: tls-cql-port
  selector:
    app: dse
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: dse
spec:
  serviceName: "dse"
  replicas: 3
  podManagementPolicy: OrderedReady
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: dse
    spec:
      securityContext:
        fsGroup: 999
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - dse
            topologyKey: kubernetes.io/hostname
      containers:
      - name: dse
        image: gcr.io/datastax-public/dse-server:6.0.0
        args: [ "dse", "cassandra", "-f"]
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: "1"
            memory: "3000Mi"
        env:
        - name: DS_LICENSE
          value: accept
        - name: SEEDS
          value: dse-0.dse.dse.svc.cluster.local,dse-1.dse.dse.svc.cluster.local
        - name: CLUSTER_NAME
          value: "Test Cluster"
        - name: NUM_TOKENS
          value: "64"
        - name: DC
          value: "DC-1"
        - name: RACK
          value: "rack-1"
        - name: DSE_DATA
          value: dse-data
        - name: OPSCENTER_IP
          value: opscenter-0.opscenter.dse.svc.cluster.local
        ports:
        - containerPort: 7001
          name: tls-intra-node
        - containerPort: 7199
          name: jmx-port
        - containerPort: 8609
          name: inter-node-msg
        - containerPort: 9142
          name: tls-cql-port
        - containerPort: 61621
          name: ds-agent-port
        volumeMounts:
        - name: dse-data
          mountPath: /dse-data
        - name: config-volume
          mountPath: /config
        - name: secrets-volume
          mountPath: /secrets
        livenessProbe:
          tcpSocket:
            port: 9142
          initialDelaySeconds: 900
          timeoutSeconds: 1
          periodSeconds: 30
          failureThreshold: 10
      volumes:
      - name: config-volume
        configMap:
          name: dse-config
      - name: secrets-volume
        secret:
          secretName: dse-secrets
          items:
          - key: identity.jks
            path: .keystore
          - key: cacerts #TODO this should be a configMap, but k8s doesn't support binary files in config maps until 1.10 (we're on 1.9)
            path: cacerts
          - key: identity.pkcs8.pem
            path: identity.pkcs8.pem
  volumeClaimTemplates:
  - metadata:
      name: dse-data
      annotations:
        volume.beta.kubernetes.io/storage-class: fast
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 8Gi
---
apiVersion: batch/v1
kind: Job
metadata:
  name: dse-cluster-init-job
  labels:
    app: dse
spec:
  template:
    spec:
      containers:
      - name: dse-cluster-init
        image: gcr.io/datastax-public/dse-cluster-init:6.0.0
        imagePullPolicy: IfNotPresent
        env:
        - name: SEED_DNS
          value: dse-0.dse.dse.svc.cluster.local
        - name: OPSC_DNS
          value: opscenter-0.opscenter.dse.svc.cluster.local
      restartPolicy: Never
  backoffLimit: 8
