apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: fast
provisioner: kubernetes.io/aws-ebs
parameters:
  type: io1
  iopsPerGB: "1"
  fsType: ext4
---
apiVersion: v1
kind: Service
metadata:
  name: opscenter-ext-lb
  labels:
    app: opscenter
spec:
  type: NodePort
  ports:
  - port: 8888
    nodePort: 30888
    name: opsc-gui-port
  - port: 8443
    nodePort: 30843
    name: opsc-secure-port
  selector:
    app: opscenter
---
apiVersion: v1
kind: Service
metadata:
  name: opscenter
  labels:
    app: opscenter
spec:
  ports:
  - port: 8888
    name: opsc-gui-port
  - port: 8443
    name: opsc-secure-port
  - port: 61620
    name: port-61620
  clusterIP: None
  selector:
    app: opscenter
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: opscenter
spec:
  serviceName: "opscenter"
  replicas: 1
  template:
    metadata:
      labels:
        app: opscenter
    spec:
      containers:
        - name: opscenter
          image: gcr.io/datastax-public/dse-opscenter:6.5.0
          imagePullPolicy: IfNotPresent
          lifecycle:
            postStart:
              exec:
                command: ["/update_admin_password.sh"]
          resources:
            requests:
              cpu: "1"
              memory: "4000Mi"
          env:
          - name: DS_LICENSE
            value: accept
          - name: OPSC_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: opsc
                key: admin_password 
          ports:
          - containerPort: 8888
            name: opsc-gui-port
          - containerPort: 61620
            name: port-61620
          volumeMounts:
          - name: config-volume
            mountPath: /config
          - name: config-clusters-volume
            mountPath: /opt/opscenter/conf/clusters
          - name: ssl-store-volume
            mountPath: /var/lib/opscenter/ssl
          - name: secrets-volume
            mountPath: /secrets
      volumes:
      - name: config-volume
        configMap:
          name: opsc-config
      - name: config-clusters-volume
        emptyDir: {}
      - name: ssl-store-volume
        configMap:
          name: opsc-ssl-config
      - name: secrets-volume
        secret:
          secretName: dse-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: dse 
  labels:
    app: dse
spec:
  ports:
  - port: 9142
    name: tls-cql-port
  clusterIP: None
  selector:
    app: dse
---
apiVersion: v1
kind: Service
metadata:
  name: dse-lb
  labels:
    app: dse
spec:
  type: NodePort
  ports:
  - port: 9142
    nodePort: 30943
    name: tls-cql-port
  selector:
    app: dse
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: dse
spec:
  serviceName: "dse"
  replicas: 3
  podManagementPolicy: OrderedReady
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: dse
    spec:
      securityContext:
        fsGroup: 999
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - dse
            topologyKey: kubernetes.io/hostname
      initContainers:
      - name: init-opsc-up
        image: tutum/curl
        command: ['sh', '-c', 'until curl -k https://${OPSC_DNS}:8443; do echo waiting for OPSC; sleep 5; done;']
        env:
        - name: OPSC_DNS
          value: opscenter-0.opscenter.dse.svc.cluster.local
      containers:
      - name: dse
        image: rs017991/dse-server:0.0.2
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: "1"
            memory: 4000Mi
        env:
        - name: DS_LICENSE
          value: accept
        - name: SEEDS
          value: dse-0.dse.dse.svc.cluster.local,dse-1.dse.dse.svc.cluster.local
        - name: CLUSTER_NAME
          value: PKS_Dev
        - name: NUM_TOKENS
          value: "64"
        - name: DC
          value: realtime
        - name: RACK
          value: NA
        - name: OPSCENTER_IP
          value: opscenter-0.opscenter.dse.svc.cluster.local
        - name: LOCAL_JMX
          value: 'no'
        - name: JVM_EXTRA_OPTS
          value: '-Dcom.sun.management.jmxremote.password.file=/secrets/jmxremote.password'
        ports:
        - containerPort: 7001
          name: tls-intra-node
        - containerPort: 7199
          name: jmx-port
        - containerPort: 8609
          name: inter-node-msg
        - containerPort: 9142
          name: tls-cql-port
        - containerPort: 61621
          name: ds-agent-port
        volumeMounts:
        - name: dse-data
          mountPath: /var/lib/cassandra
        - name: config-volume
          mountPath: /config
        - name: secrets-volume
          mountPath: /secrets
        livenessProbe:
          tcpSocket:
            port: 9142
          initialDelaySeconds: 100
          timeoutSeconds: 1
          periodSeconds: 10
          failureThreshold: 10
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "exec nodetool decommission"]
      volumes:
      - name: config-volume
        configMap:
          name: dse-config
      - name: secrets-volume
        secret:
          secretName: dse-secrets
  volumeClaimTemplates:
  - metadata:
      name: dse-data
      annotations:
        volume.beta.kubernetes.io/storage-class: fast
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 8Gi
---
apiVersion: batch/v1
kind: Job
metadata:
  name: dse-cluster-init-job
  labels:
    app: dse
spec:
  template:
    spec:
      initContainers:
      - name: init-opsc-up
        image: tutum/curl
        command: ['sh', '-c', 'until curl -k https://${OPSC_DNS}:8443; do echo waiting for OPSC; sleep 5; done;']
        env:
        - name: OPSC_DNS
          value: opscenter-0.opscenter.dse.svc.cluster.local
      containers:
      - name: dse-cluster-init
        image: rs017991/dse-cluster-init:0.0.3
        imagePullPolicy: IfNotPresent
        env:
        - name: SEED_DNS
          value: dse-0.dse.dse.svc.cluster.local,dse-1.dse.dse.svc.cluster.local
        - name: CLUSTER_NAME
          value: PKS_Dev
        - name: CLUSTER_SIZE
          value: "3"
        - name: OPSC_DNS
          value: opscenter-0.opscenter.dse.svc.cluster.local
        - name: OPSC_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: opsc
              key: admin_password
        - name: CLUSTER_FILE
          value: /cluster-config/config.json
        volumeMounts:
        - name: cluster-config
          mountPath: /cluster-config
      volumes:
      - name: cluster-config
        secret:
          secretName: cluster-config
      restartPolicy: Never
  backoffLimit: 8
